/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2World */

#ifndef _Included_org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2World
#define _Included_org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2World
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2World
 * Method:    malloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2World_malloc
  (JNIEnv *, jobject);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2World
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2World_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2World
 * Method:    getLilvPlugins
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2World_getLilvPlugins
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
