/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTPlugin */

#ifndef _Included_org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTPlugin
#define _Included_org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTPlugin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTPlugin
 * Method:    malloc
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTPlugin_malloc
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTPlugin
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTPlugin_delete
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTPlugin
 * Method:    initEffect
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTPlugin_initEffect
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
