/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth */

#ifndef _Included_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
#define _Included_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    malloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_malloc
  (JNIEnv *, jobject);

/*
 * Class:     app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    open
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_open
  (JNIEnv *, jobject, jlong);

/*
 * Class:     app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    loadFont
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_loadFont
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    unloadFont
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_unloadFont
  (JNIEnv *, jobject, jlong);

/*
 * Class:     app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    systemReset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_systemReset
  (JNIEnv *, jobject, jlong);

/*
 * Class:     app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    noteOn
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_noteOn
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    noteOff
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_noteOff
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    controlChange
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_controlChange
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    programChange
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_programChange
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    pitchBend
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_pitchBend
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    setDoubleProperty
 * Signature: (JLjava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_setDoubleProperty
  (JNIEnv *, jobject, jlong, jstring, jdouble);

/*
 * Class:     app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    setIntegerProperty
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_setIntegerProperty
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    setStringProperty
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_setStringProperty
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    getDoubleProperty
 * Signature: (JLjava/lang/String;Lapp/tuxguitar/player/impl/midiport/fluidsynth/type/DoubleRef;)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_getDoubleProperty
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    getIntegerProperty
 * Signature: (JLjava/lang/String;Lapp/tuxguitar/player/impl/midiport/fluidsynth/type/IntegerRef;)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_getIntegerProperty
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    getStringProperty
 * Signature: (JLjava/lang/String;Lapp/tuxguitar/player/impl/midiport/fluidsynth/type/StringRef;)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_getStringProperty
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    getDoublePropertyDefault
 * Signature: (JLjava/lang/String;Lapp/tuxguitar/player/impl/midiport/fluidsynth/type/DoubleRef;)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_getDoublePropertyDefault
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    getIntegerPropertyDefault
 * Signature: (JLjava/lang/String;Lapp/tuxguitar/player/impl/midiport/fluidsynth/type/IntegerRef;)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_getIntegerPropertyDefault
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    getStringPropertyDefault
 * Signature: (JLjava/lang/String;Lapp/tuxguitar/player/impl/midiport/fluidsynth/type/StringRef;)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_getStringPropertyDefault
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    getDoublePropertyRange
 * Signature: (JLjava/lang/String;Lapp/tuxguitar/player/impl/midiport/fluidsynth/type/DoubleRef;Lapp/tuxguitar/player/impl/midiport/fluidsynth/type/DoubleRef;)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_getDoublePropertyRange
  (JNIEnv *, jobject, jlong, jstring, jobject, jobject);

/*
 * Class:     app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    getIntegerPropertyRange
 * Signature: (JLjava/lang/String;Lapp/tuxguitar/player/impl/midiport/fluidsynth/type/IntegerRef;Lapp/tuxguitar/player/impl/midiport/fluidsynth/type/IntegerRef;)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_getIntegerPropertyRange
  (JNIEnv *, jobject, jlong, jstring, jobject, jobject);

/*
 * Class:     app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    getPropertyOptions
 * Signature: (JLjava/lang/String;Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_getPropertyOptions
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    isRealtimeProperty
 * Signature: (JLjava/lang/String;Lapp/tuxguitar/player/impl/midiport/fluidsynth/type/BooleanRef;)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_isRealtimeProperty
  (JNIEnv *, jobject, jlong, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
