/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_herac_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth */

#ifndef _Included_org_herac_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
#define _Included_org_herac_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    malloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_herac_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_malloc
  (JNIEnv *, jobject);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    loadDriver
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_loadDriver
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    loadFont
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_loadFont
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    unloadFont
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_unloadFont
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    systemReset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_systemReset
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    noteOn
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_noteOn
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    noteOff
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_noteOff
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    controlChange
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_controlChange
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    programChange
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_programChange
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth
 * Method:    pitchBend
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_fluidsynth_MidiSynth_pitchBend
  (JNIEnv *, jobject, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
