@ECHO OFF

::SCRIPT DIR
SET "TG_START=%cd%"
cd %~dp0
SET "TG_DIR=."
::JAVA
SET "JAVA=jre\bin\java"
::LIBRARY_PATH
SET "JAVA_LIBRARY_PATH=%JAVA_LIBRARY_PATH%;lib\"
::CLASSPATH
SET "JAVA_CLASSPATH=%JAVA_CLASSPATH%;lib\*"
SET "JAVA_CLASSPATH=%JAVA_CLASSPATH%;share\"
SET "JAVA_CLASSPATH=%JAVA_CLASSPATH%;dist\"
::MAINCLASS
SET "TG_MAIN_CLASS=app.tuxguitar.app.TGMainSingleton"
::LAUNCH
%JAVA% -cp %JAVA_CLASSPATH% -Dtuxguitar.home.path=%TG_DIR% -Djava.library.path=%JAVA_LIBRARY_PATH% %TG_MAIN_CLASS% %1 %2 %3 %4 %5 %6 %7 %8 %9 %10
cd %TG_START%
