/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect */

#ifndef _Included_org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect
#define _Included_org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect
 * Method:    malloc
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect_malloc
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect
 * Method:    delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect_delete
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect
 * Method:    openEffect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect_openEffect
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect
 * Method:    closeEffect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect_closeEffect
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect
 * Method:    getNumParams
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect_getNumParams
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect
 * Method:    getNumInputs
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect_getNumInputs
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect
 * Method:    getNumOutputs
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect_getNumOutputs
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect
 * Method:    setBlockSize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect_setBlockSize
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect
 * Method:    setSampleRate
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect_setSampleRate
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect
 * Method:    setParameter
 * Signature: (JIF)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect_setParameter
  (JNIEnv *, jobject, jlong, jint, jfloat);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect
 * Method:    getParameter
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect_getParameter
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect
 * Method:    getParameterName
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect_getParameterName
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect
 * Method:    getParameterLabel
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect_getParameterLabel
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect
 * Method:    sendMessages
 * Signature: (J[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect_sendMessages
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect
 * Method:    sendProcessReplacing
 * Signature: (J[[F[[FI)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_vst_jni_VSTEffect_sendProcessReplacing
  (JNIEnv *, jobject, jlong, jobjectArray, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
