package org.herac.tuxguitar.song.models;

public class TGChannelNames {
	
	public static final String[] DEFAULT_NAMES = {
		("Piano"),
		("Bright Piano"),
		("Electric Grand"),
		("Honky Tonk Piano"),
		("Electric Piano 1"),
		("Electric Piano 2"),
		("Harpsichord"),
		("Clavinet"),
		("Celesta"),
		("Glockenspiel"),
		("Music Box"),
		("Vibraphone"),
		("Marimba"),
		("Xylophone"),
		("Tubular Bell"),
		("Dulcimer"),
		("Hammond Organ"),
		("Perc Organ"),
		("Rock Organ"),
		("Church Organ"),
		("Reed Organ"),
		("Accordion"),
		("Harmonica"),
		("Tango Accordion"),
		("Nylon Str Guitar"),
		("Steel String Guitar"),
		("Jazz Electric Gtr"),
		("Clean Guitar"),
		("Muted Guitar"),
		("Overdrive Guitar"),
		("Distortion Guitar"),
		("Guitar Harmonics"),
		("Acoustic Bass"),
		("Fingered Bass"),
		("Picked Bass"),
		("Fretless Bass"),
		("Slap Bass 1"),
		("Slap Bass 2"),
		("Syn Bass 1"),
		("Syn Bass 2"),
		("Violin"),
		("Viola"),
		("Cello"),
		("Contrabass"),
		("Tremolo Strings"),
		("Pizzicato Strings"),
		("Orchestral Harp"),
		("Timpani"),
		("Ensemble Strings"),
		("Slow Strings"),
		("Synth Strings 1"),
		("Synth Strings 2"),
		("Choir Aahs"),
		("Voice Oohs"),
		("Syn Choir"),
		("Orchestra Hit"),
		("Trumpet"),
		("Trombone"),
		("Tuba"),
		("Muted Trumpet"),
		("French Horn"),
		("Brass Ensemble"),
		("Syn Brass 1"),
		("Syn Brass 2"),
		("Soprano Sax"),
		("Alto Sax"),
		("Tenor Sax"),
		("Baritone Sax"),
		("Oboe"),
		("English Horn"),
		("Bassoon"),
		("Clarinet"),
		("Piccolo"),
		("Flute"),
		("Recorder"),
		("Pan Flute"),
		("Bottle Blow"),
		("Shakuhachi"),
		("Whistle"),
		("Ocarina"),
		("Syn Square Wave"),
		("Syn Saw Wave"),
		("Syn Calliope"),
		("Syn Chiff"),
		("Syn Charang"),
		("Syn Voice"),
		("Syn Fifths Saw"),
		("Syn Brass and Lead"),
		("Fantasia"),
		("Warm Pad"),
		("Polysynth"),
		("Space Vox"),
		("Bowed Glass"),
		("Metal Pad"),
		("Halo Pad"),
		("Sweep Pad"),
		("Ice Rain"),
		("Soundtrack"),
		("Crystal"),
		("Atmosphere"),
		("Brightness"),
		("Goblins"),
		("Echo Drops"),
		("Sci Fi"),
		("Sitar"),
		("Banjo"),
		("Shamisen"),
		("Koto"),
		("Kalimba"),
		("Bag Pipe"),
		("Fiddle"),
		("Shanai"),
		("Tinkle Bell"),
		("Agogo"),
		("Steel Drums"),
		("Woodblock"),
		("Taiko Drum"),
		("Melodic Tom"),
		("Syn Drum"),
		("Reverse Cymbal"),
		("Guitar Fret Noise"),
		("Breath Noise"),
		("Seashore"),
		("Bird"),
		("Telephone"),
		("Helicopter"),
		("Applause"),
		("Gunshot")
	};
}
