.TH "TUXGUITAR" "1" 
.SH "NAME" 
tuxguitar \(em program to do edit and playback guitar tablature 
.SH "SYNOPSIS" 
.PP 
\fBtuxguitar\fR [ \fB-h\fP | \fB\-\-help\fP  ]  [ \fB-v\fP | \fB\-\-version\fP  ]  [ \fB-i\fP | \fB\-\-system-info\fP  ]  [ \fB-D\fIname\fR=\fIvalue\fR\fP  ]  [  \fISONG.tg\fR  ]  
.SH "DESCRIPTION" 
.PP 
tuxguitar supports guitar pro format and exports to pdf and midi. 
.PP 
This manual page was written for the \fBDebian\fP distribution 
because the original program does not have a manual page. 
.SH "WWW" 
.PP 
http://www.tuxguitar.com.ar 
.SH "AUTHOR" 
.PP 
This manual page was written by Philippe Coval rzr@users.sf.net for 
the \fBDebian\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any  
later version published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL. 
 
.\" created by instant / docbook-to-man, Wed 16 Apr 2008, 18:33 
