/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_tuxguitar_player_impl_midiport_alsa_MidiSystem */

#ifndef _Included_app_tuxguitar_player_impl_midiport_alsa_MidiSystem
#define _Included_app_tuxguitar_player_impl_midiport_alsa_MidiSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_tuxguitar_player_impl_midiport_alsa_MidiSystem
 * Method:    malloc
 * Signature: ()I
 */
JNIEXPORT jlong JNICALL Java_app_tuxguitar_player_impl_midiport_alsa_MidiSystem_malloc
  (JNIEnv *, jobject);

/*
 * Class:     app_tuxguitar_player_impl_midiport_alsa_MidiSystem
 * Method:    free
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_alsa_MidiSystem_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     app_tuxguitar_player_impl_midiport_alsa_MidiSystem
 * Method:    open
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_alsa_MidiSystem_open
  (JNIEnv *, jobject, jlong);

/*
 * Class:     app_tuxguitar_player_impl_midiport_alsa_MidiSystem
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_alsa_MidiSystem_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     app_tuxguitar_player_impl_midiport_alsa_MidiSystem
 * Method:    findPorts
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_alsa_MidiSystem_findPorts
  (JNIEnv *, jobject, jlong);

/*
 * Class:     app_tuxguitar_player_impl_midiport_alsa_MidiSystem
 * Method:    openPort
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_alsa_MidiSystem_openPort
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     app_tuxguitar_player_impl_midiport_alsa_MidiSystem
 * Method:    closePort
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_alsa_MidiSystem_closePort
  (JNIEnv *, jobject, jlong);

/*
 * Class:     app_tuxguitar_player_impl_midiport_alsa_MidiSystem
 * Method:    noteOn
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_alsa_MidiSystem_noteOn
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     app_tuxguitar_player_impl_midiport_alsa_MidiSystem
 * Method:    noteOff
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_alsa_MidiSystem_noteOff
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     app_tuxguitar_player_impl_midiport_alsa_MidiSystem
 * Method:    controlChange
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_alsa_MidiSystem_controlChange
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     app_tuxguitar_player_impl_midiport_alsa_MidiSystem
 * Method:    programChange
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_alsa_MidiSystem_programChange
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     app_tuxguitar_player_impl_midiport_alsa_MidiSystem
 * Method:    pitchBend
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_app_tuxguitar_player_impl_midiport_alsa_MidiSystem_pitchBend
  (JNIEnv *, jobject, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
