/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem */

#ifndef _Included_org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem
#define _Included_org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem
 * Method:    malloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem_malloc
  (JNIEnv *, jobject);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem
 * Method:    open
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem_open
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem
 * Method:    findPorts
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem_findPorts
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem
 * Method:    openPort
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem_openPort
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem
 * Method:    closePort
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem_closePort
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem
 * Method:    noteOn
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem_noteOn
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem
 * Method:    noteOff
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem_noteOff
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem
 * Method:    controlChange
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem_controlChange
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem
 * Method:    programChange
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem_programChange
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem
 * Method:    pitchBend
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_winmm_MidiSystem_pitchBend
  (JNIEnv *, jobject, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
