/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class org_herac_tuxguitar_player_impl_midiport_alsa_MidiReceiverJNI */

#ifndef _Included_org_herac_tuxguitar_player_impl_midiport_audiounit_MidiReceiverJNI
#define _Included_org_herac_tuxguitar_player_impl_midiport_audiounit_MidiReceiverJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_alsa_MidiReceiverJNI
 * Method:    open
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_audiounit_MidiReceiverJNI_open
  (JNIEnv *, jobject);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_alsa_MidiReceiverJNI
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_audiounit_MidiReceiverJNI_close
  (JNIEnv *, jobject);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_alsa_MidiReceiverJNI
 * Method:    openDevice
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_audiounit_MidiReceiverJNI_openDevice
  (JNIEnv *, jobject);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_alsa_MidiReceiverJNI
 * Method:    closeDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_audiounit_MidiReceiverJNI_closeDevice
  (JNIEnv *, jobject);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_alsa_MidiReceiverJNI
 * Method:    noteOn
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_audiounit_MidiReceiverJNI_noteOn
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_alsa_MidiReceiverJNI
 * Method:    noteOff
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_audiounit_MidiReceiverJNI_noteOff
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_alsa_MidiReceiverJNI
 * Method:    controlChange
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_audiounit_MidiReceiverJNI_controlChange
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_alsa_MidiReceiverJNI
 * Method:    programChange
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_audiounit_MidiReceiverJNI_programChange
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_alsa_MidiReceiverJNI
 * Method:    pitchBend
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_audiounit_MidiReceiverJNI_pitchBend
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
