/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_herac_tuxguitar_carbon_opendoc_OpenDocJNI */

#ifndef _Included_org_herac_tuxguitar_carbon_opendoc_OpenDocJNI
#define _Included_org_herac_tuxguitar_carbon_opendoc_OpenDocJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_herac_tuxguitar_carbon_opendoc_OpenDocJNI
 * Method:    AEGetParamDesc
 * Signature: (IIILorg/eclipse/swt/internal/carbon/AEDesc;)I
 */
JNIEXPORT jint JNICALL Java_org_herac_tuxguitar_carbon_opendoc_OpenDocJNI_AEGetParamDesc
  (JNIEnv *, jclass, jint, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
