/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Plugin */

#ifndef _Included_org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Plugin
#define _Included_org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Plugin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Plugin
 * Method:    malloc
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Plugin_malloc
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Plugin
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Plugin_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Plugin
 * Method:    getUri
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Plugin_getUri
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Plugin
 * Method:    getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Plugin_getName
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
