/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Instance */

#ifndef _Included_org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Instance
#define _Included_org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Instance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Instance
 * Method:    malloc
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Instance_malloc
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Instance
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Instance_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Instance
 * Method:    getInputPortCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Instance_getInputPortCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Instance
 * Method:    getOutputPortCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Instance_getOutputPortCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Instance
 * Method:    setControlPortValue
 * Signature: (JIF)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Instance_setControlPortValue
  (JNIEnv *, jobject, jlong, jint, jfloat);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Instance
 * Method:    getControlPortValue
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Instance_getControlPortValue
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Instance
 * Method:    getControlPortInfo
 * Signature: (JI)Lorg/herac/tuxguitar/player/impl/midiport/lv2/jni/LV2ControlPortInfo;
 */
JNIEXPORT jobject JNICALL Java_org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Instance_getControlPortInfo
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Instance
 * Method:    getControlPortIndices
 * Signature: (J)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Instance_getControlPortIndices
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Instance
 * Method:    processAudio
 * Signature: (J[[F[[F)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_player_impl_midiport_lv2_jni_LV2Instance_processAudio
  (JNIEnv *, jobject, jlong, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
